### ISSUE TITLE
Bug on recursive get value

### ISSUE THREAD

**Issue by heroselohim** [kohkimakimoto/EArray#6]
Here I'm posting a fix when using custom delimiters. I'm using dot as delimiter. By the way, this class is awesome! Thanks

    public function get($key, $default = null, $delimiter = null)
    {
        if ($delimiter === null) {     <-----------
            $delimiter = $this->delimiter;      <-----------
        }       <-----------

        $ret = $this->getRawValue($key, $default, $delimiter);
        if (is_array($ret)) {
            $ret = new EArray($ret, $delimiter);     <----------
        }

        return $ret;
    }

Sorry, formatting of text is not working for me.

**Comment by kohkimakimoto** [comment]
@heroselohim Thanks your report and suggestion. I fixed the code by #7. and released new version v2.3.0.
